// 在真实宿主页中验证插件交互并生成截图
const assert = require('node:assert/strict');
const {createRequire} = require('node:module');
const {chromium} = createRequire(process.env.PLAYWRIGHT_PACKAGE)('playwright');
const base = process.env.CPR_TEST_BASE;
(async () => {
  const browser = await chromium.launch({executablePath:process.env.CHROMIUM_PATH,headless:true,args:['--no-sandbox']});
  try {
    const context = await browser.newContext({viewport:{width:1280,height:850}});
    await context.request.post(base+'/api/auth/login',{data:{mode:'admin',username:'admin@quota.test',password:'quota-guard-test-only'}});
    await context.addCookies((await context.cookies()).map(c=>({...c,secure:false})));
    const instances = await (await context.request.get(base+'/api/admin/plugins/instances')).json();
    const id = instances.data[0].id;
    const page = await context.newPage();
    const errors=[];
    page.on('pageerror', e=>errors.push(e.message));
    await page.goto(base+'/plugins/'+id+'/guard');
    const frame=page.frameLocator('iframe');
    await frame.locator('.account-row').first().waitFor();
    const refresh=frame.getByRole('button',{name:'刷新列表',exact:true});
    assert.equal(await frame.getByRole('tooltip').first().isVisible(),false);
    await refresh.focus();
    await frame.getByRole('tooltip').first().waitFor({state:'visible'});
    assert.equal(await frame.getByRole('tooltip').first().innerText(),'刷新列表，仅读取CPR已有数据，不会请求上游');
    await refresh.click();
    await frame.getByRole('status').filter({hasText:'列表已更新'}).waitFor();
    const a=frame.locator('.account-row').filter({hasText:'验证账号 A'});
    await a.getByRole('button',{name:'设置账号保护'}).click();
    await frame.getByLabel('固定阈值').fill('200');
    await frame.getByRole('button',{name:'保存',exact:true}).click();
    await frame.getByRole('alert').filter({hasText:'阈值须为'}).waitFor();
    await frame.getByLabel('固定阈值').fill('5');
    await frame.getByRole('button',{name:'取消',exact:true}).click();
    assert.match(await a.innerText(),/固定 15%/);
    await a.getByRole('button',{name:'设置账号保护'}).click();
    await frame.getByLabel('固定阈值').fill('14');
    await frame.getByRole('button',{name:'保存',exact:true}).click();
    await frame.getByRole('dialog').waitFor({state:'hidden'});
    assert.match(await a.innerText(),/固定 14%/);
    await a.getByRole('button',{name:'设置账号保护'}).click();
    await frame.getByLabel('固定阈值').fill('15');
    await frame.getByRole('button',{name:'保存',exact:true}).click();
    await frame.getByRole('dialog').waitFor({state:'hidden'});
    const b=frame.locator('.account-row').filter({hasText:'验证账号 B'});
    assert.match(await b.innerText(),/下周期：随机 30%–40%/);
    await b.getByRole('button',{name:'设置账号保护'}).click();
    await frame.getByLabel('随机下限').fill('90');
    await frame.getByLabel('随机上限').fill('20');
    await frame.getByRole('button',{name:'保存',exact:true}).click();
    await frame.getByRole('alert').filter({hasText:'下限不大于上限'}).waitFor();
    await page.waitForTimeout(300);
    await page.screenshot({path:'validation/output/invalid-range.png',fullPage:true});
    await frame.getByRole('button',{name:'取消',exact:true}).click();
    await frame.getByRole('button',{name:'添加账号',exact:true}).click();
    await frame.getByRole('combobox').first().click();
    await frame.getByRole('option',{name:'验证账号 C',exact:true}).click();
    const toggle=frame.getByRole('switch',{name:'启用保护'});
    assert.equal(await toggle.isChecked(),true);
    await toggle.focus();await toggle.press('Space');
    assert.equal(await toggle.isChecked(),false);
    await frame.getByRole('button',{name:'保存',exact:true}).click();
    await frame.getByRole('dialog').waitFor({state:'hidden'});
    assert.match(await frame.locator('.account-row').filter({hasText:'验证账号 C'}).innerText(),/保护已关闭/);
    await refresh.click();
    await frame.getByRole('status').filter({hasText:'列表已更新'}).waitFor();
    await page.mouse.move(400,80);
    await frame.locator('main').click({position:{x:12,y:8}});
    await page.waitForTimeout(300);
    await page.screenshot({path:'docs/images/overview.png',fullPage:true});
    await page.getByRole('button',{name:'切换暗黑模式'}).click();
    await page.waitForTimeout(400);
    await page.screenshot({path:'validation/output/dark.png',fullPage:true});
    const colors=await frame.locator('body').evaluate(e=>({color:getComputedStyle(e).color,bg:getComputedStyle(e).backgroundColor}));
    await page.setViewportSize({width:390,height:844});
    await page.waitForTimeout(350);
    assert.equal(await frame.locator('body').evaluate(e=>e.scrollWidth<=innerWidth+1),true);
    await page.screenshot({path:'validation/output/mobile-dark.png',fullPage:true});
    await page.getByRole('button',{name:'切换亮色模式'}).click().catch(()=>{});
    assert.deepEqual(errors,[]);
    console.log('PASS 真实管理桥、刷新提示、固定编辑、取消、输入错误、随机待生效、添加、开关、明暗与窄屏',colors);
  } finally { await browser.close(); }
})().catch(e=>{console.error(e);process.exitCode=1});
